local_costmap:
  global_frame: rosbot1/odom
  robot_base_frame: rosbot1/base_link

  update_frequency: 2.5
  publish_frequency: 2.5
  transform_tolerance: 0.25
  static_map: false
  rolling_window: true
  width: 3
  height: 3
  origin_x: -1.5
  origin_y: -1.5
  resolution: 0.01
  inflation_radius: 0.5 #1.0 # parameter to obstacle avoidance, the higher it is, the higher the penalty is when it s closer of an obstacle  cost_scaling_factor
  cost_scaling_factor: 2
